apiVersion: v1
kind: Service

metadata:
  name: inode-service
  namespace: inode

spec:

  type: NodePort

  selector:
    app: inode

  ports:

    - port: 9090
      targetPort: 9090
      nodePort: 30090
